Repository Team-kiwing/Team-3seco-kiwing-be, pull requests merged in 2024-03, with the labels that each got.

#50 feat: 꾸러미 삭제 시 count 필드들 감소 로직 추가 및 커스텀 update 쿼리문 작성
  data/src/main/kotlin/com/kw/data/domain/bundle/Bundle.kt
  data/src/main/kotlin/com/kw/data/domain/bundle/repository/BundleRepository.kt
  data/src/main/kotlin/com/kw/data/domain/question/Question.kt
  data/src/main/kotlin/com/kw/data/domain/question/repository/QuestionRepository.kt
  infra/infra-redis/build.gradle.kts
  infra/infra-redis/src/main/kotlin/com/kw/infraredis/config/RedisConfig.kt
  infra/infra-security/src/main/kotlin/com/kw/infrasecurity/config/WebSecurityConfig.kt
  infra/infra-security/src/main/kotlin/com/kw/infrasecurity/jwt/JwtAuthenticationFilter.kt
  infra/infra-security/src/main/kotlin/com/kw/infrasecurity/resolver/AuthToMemberArgumentResolver.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/service/BundleService.kt
  server/api/src/test/kotlin/com/kw/api/domain/bundle/service/BundleServiceTest.kt
Labels: ✨ Feature

#54 refactor: ApiResponse 제거
  server/api/src/main/kotlin/com/kw/api/common/dto/response/ApiResponse.kt
  server/api/src/main/kotlin/com/kw/api/domain/auth/controller/AuthController.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/controller/BundleController.kt
  server/api/src/main/kotlin/com/kw/api/domain/claim/controller/ClaimController.kt
  server/api/src/main/kotlin/com/kw/api/domain/member/controller/MemberController.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/controller/QuestionController.kt
  server/api/src/main/kotlin/com/kw/api/domain/tag/controller/TagController.kt
Labels: 🔨 Refactor

#61 feat: 꾸러미 순서 변경 기능 구현
  data/src/main/kotlin/com/kw/data/domain/bundle/Bundle.kt
  data/src/main/kotlin/com/kw/data/domain/bundle/dto/request/BundleGetCondition.kt
  data/src/main/kotlin/com/kw/data/domain/bundle/repository/BundleCustomRepositoryImpl.kt
  data/src/main/kotlin/com/kw/data/domain/member/Member.kt
  infra/infra-security/src/main/kotlin/com/kw/infrasecurity/config/WebSecurityConfig.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/controller/BundleController.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/service/BundleService.kt
  server/api/src/main/kotlin/com/kw/api/domain/member/controller/MemberController.kt
  server/api/src/main/kotlin/com/kw/api/domain/member/dto/request/BundleOrderUpdateRequest.kt
  server/api/src/main/kotlin/com/kw/api/domain/member/service/MemberService.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/service/QuestionService.kt
Labels: ✨ Feature

#77 fix: keyword 검색 쿼리 LIKE -> MATCH 쿼리로 수정
  data/src/main/kotlin/com/kw/data/common/contributor/MatchFunctionContributor.kt
  data/src/main/kotlin/com/kw/data/common/util/CustomFunction.kt
  data/src/main/kotlin/com/kw/data/domain/bundle/repository/BundleCustomRepositoryImpl.kt
  data/src/main/kotlin/com/kw/data/domain/question/repository/QuestionCustomRepositoryImpl.kt
  data/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: ⚒️ Fix

#82 feat: Question isSearchable 추가
  data/src/main/kotlin/com/kw/data/domain/bundle/repository/BundleCustomRepository.kt
  data/src/main/kotlin/com/kw/data/domain/bundle/repository/BundleCustomRepositoryImpl.kt
  data/src/main/kotlin/com/kw/data/domain/question/Question.kt
  data/src/main/kotlin/com/kw/data/domain/question/repository/QuestionCustomRepository.kt
  data/src/main/kotlin/com/kw/data/domain/question/repository/QuestionCustomRepositoryImpl.kt
  data/src/main/kotlin/com/kw/data/domain/question/repository/QuestionRepository.kt
  data/src/main/resources/schema.sql
  server/api/src/main/kotlin/com/kw/api/domain/bundle/service/BundleService.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/dto/request/QuestionCreateRequest.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/service/QuestionService.kt
Labels: ✨ Feature

#85 chore: 인증 관련 에러 메시지 변경
  infra/infra-security/src/main/kotlin/com/kw/infrasecurity/util/HttpResponseUtil.kt
Labels: 🔨 Refactor

#88 feat: 조회 수, 노출 수 증가 로직 추가
  data/src/main/kotlin/com/kw/data/domain/bundle/Bundle.kt
  data/src/main/kotlin/com/kw/data/domain/bundle/repository/BundleRepository.kt
  data/src/main/kotlin/com/kw/data/domain/question/Question.kt
  data/src/main/kotlin/com/kw/data/domain/question/repository/QuestionRepository.kt
  data/src/main/resources/schema.sql
  server/api/src/main/kotlin/com/kw/api/domain/bundle/service/BundleService.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/service/QuestionService.kt
Labels: ✨ Feature

#102 feat: popularity isHot 연동
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .gitignore
  data/src/main/kotlin/com/kw/data/domain/bundle/Bundle.kt
  data/src/main/kotlin/com/kw/data/domain/question/Question.kt
  server/api/src/main/kotlin/com/kw/api/ApiApplication.kt
  server/api/src/main/kotlin/com/kw/api/common/properties/ApiProperties.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/dto/response/BundleDetailResponse.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/dto/response/BundleResponse.kt
  server/api/src/main/kotlin/com/kw/api/domain/bundle/service/BundleService.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/dto/response/QuestionResponse.kt
  server/api/src/main/kotlin/com/kw/api/domain/question/service/QuestionService.kt
  server/api/src/main/resources/application.yml
Labels: ✨ Feature
